CREATE TABLE Usuarios (
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
name VARCHAR (120) NOT NULL,
age INT NOT NULL,
username VARCHAR (120) NOT NULL UNIQUE,
password VARCHAR (120) NOT NULL,
email VARCHAR (120) NOT NULL UNIQUE,
countDetails VARCHAR (120) NOT NULL,
typeUser INT NOT NULL,
address VARCHAR (120) NOT NULL
)
